// <auto-generated />
namespace ArtSolution.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_PaymentRecord_Script : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_PaymentRecord_Script));
        
        string IMigrationMetadata.Id
        {
            get { return "201708210130091_Add_PaymentRecord_Script"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
